/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("bookingHeaderObjectPageObjectPage journey");

        opaTest("Navigate to bookingHeaderObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onThebookingHeaderListGenerated.onFilterBar().iExecuteSearch();
            Then.onThebookingHeaderListGenerated.onTable().iCheckRows();
            When.onThebookingHeaderListGenerated.onTable().iPressRow(0);

            Then.onThebookingHeaderObjectPageGenerated.iSeeThisPage();
        });


        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onThebookingHeaderObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "RatingHdr" });
            Then.onThebookingHeaderObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "ProgressHdr" });
            Then.onThebookingHeaderObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "PriceHdr" });
        });

        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onThebookingHeaderObjectPageGenerated.iCheckNumberOfSections(2);
            When.onThebookingHeaderObjectPageGenerated.iPressSectionIconTabFilterButton("General");
            Then.onThebookingHeaderObjectPageGenerated.iCheckSection({ section: "General" });
            When.onThebookingHeaderObjectPageGenerated.iPressSectionIconTabFilterButton("Items");
            Then.onThebookingHeaderObjectPageGenerated.iCheckSection({ section: "Items" });
            Then.onThebookingHeaderObjectPageGenerated.onTable({ property: "_bookingItem" }).iCheckColumns(undefined, {"ItemId":{"header":"Item"},"ProductId":{"header":"Product"},"Quantity":{"header":"Quantity"},"ItemPrice":{"header":"Item Price"}});
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});